(defun mx/dev-tags ()
  (setq org-tag-alist '((:startgroup . nil)
			("@file" . ?f)
			("@buffer" . ?b)
			("@window" . ?w)
			("@frame" . ?f)
			(:endgroup . nil)
			(:startgroup . nil)
			("@doc" . ?d)
			("@src" . ?s)
			("@block" . ?bl)
			("@import" . ?i)
			("@export" . ?e)
			(:endgroup . nil)
			(:startgroup . nil)
			("org" . ?o)
			("elisp" . ?el)
			("n3" . ?n3)
			("owl2" . ?owl)
			("rdfs" . ?r)
			("shell" . ?s)
			("axiom" . ?a)
			("grammar" . ?g)
			(:endgroup . nil)
			(:startgroup . nil)
			("proof" . ?p)
			("theorem" . ?t)
			("def" . ?d)
			("desc" . ?ds)
			("example" . ?ex)
			(:endgroup . nil))
	)
  )
